name: chicken_maze
description: A game with flutter and flame.
version: 1.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: ^1.0.0-releasecandidate.11

  flame_tiled: #^0.1.0
    #git:
    #  url: https://github.com/Schnurber/flame_tiled.git
    #  ref: dev
    path: ../../git/flame_tiled/
  http: ^0.13.1
  crypto: ^3.0.1
  shared_preferences: ^2.0.5
  admob_flutter: ^2.0.0-nullsafety.0
  flame_audio: ^0.1.0-rc5
  cupertino_icons: ^0.1.2
  
dev_dependencies:
  mysql1: ^0.19.0

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/images/logoChicken.png
    - assets/images/chickenIcon.png
    - assets/images/chicken.png
    - assets/images/enemy.png
    - assets/images/tiles.png
    - assets/images/grain.png
    - assets/images/pause.png
    - assets/tiles/map1.tmx
    - assets/tiles/map2.tmx
    - assets/tiles/map3.tmx
    - assets/tiles/map4.tmx
    - assets/tiles/map5.tmx
    - assets/tiles/map6.tmx
    - assets/tiles/map7.tmx
    - assets/tiles/map8.tmx
    - assets/tiles/map9.tmx
    - assets/tiles/map10.tmx
    - assets/audio/chicken.mp3
    - assets/audio/pick.mp3
    - assets/audio/cry.mp3
    - assets/audio/music.mp3

  uses-material-design: true
  fonts:
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMono-Bold.ttf
        - asset: assets/fonts/UbuntuMono-Regular.ttf
# flutter downgrade v1.22.4
# flutter run --no-sound-null-safety 